#
###################################
# Site wide configuration
####################################
#
title: Faizan Bashir
email: "faizan.ibn.bashir@gmail.com"
short_description: "DevSecOps | Cloud | Linux | AI | Programming"
description: "This blog is a unique fusion of personal experiences, philosophy, and cutting-edge technology. Delve into the world of a passionate technophile, where you'll find reflections on life's journey and insightful thoughts on the latest advancements in the tech industry, from personal anecdotes and philosophical musings to in-depth discussions of emerging technologies. My blog offers a blend of content designed to pique your curiosity, challenge your perspective, and inspire innovation. So join me as I explore the intersection of life and technology, uncovering the boundless potential that lies within."
keywords: ["devsecops", "devops", "cloud", "linux", "ai", "programming", "kubernetes", "golang", "python", "javascript", "ai", "terraform", "serverless", "webassembly", "docker", "managed kubernetes", "eks", "gke", "openshift", "nginx", "nodejs", "docker swarm", "distributed applications", "aws", "google cloud", "chatgpt", "openai", "data science", "blog", "jekyll"]
cover: assets/images/abed-ismail-cover-unsplash.webp
og-cover: assets/images/abed-ismail-cover-unsplash.webp
logo: assets/images/d3-white_resized.webp
logo_dark: assets/images/favicon.ico
favicon: assets/images/favicon.ico
url: https://www.faizanbashir.me
uri: https://www.faizanbashir.me
production_url: https://www.faizanbashir.me/
source_url: https://github.com/faizanbashir/faizanbashir.github.io/
CNAME: #add cname for website to be created

# Jekyll configuration
markdown: kramdown
highlighter: rouge
paginate: 100 # it will paginate after this number
language: 'en-uk'
words_per_minute: 200

liquid:
  error_mode: lax

# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Social info
navigation: True # show the navbar links
subscribers: False # you need to connect an external service for this to work,
# if 'True' the submit button is disabled for now, but you can change that
# by editing `_includes/subscribe-form.html`
twitter: faizanbasher # replace by your username
facebook: faizan.bashir # replace by your username
linkedin: faizan-bashir
github: faizanbashir

# Disqus
disqus: 
  enable: True
  shortname: faizanbashir # replace with your disqus username

# Google Analytics
google_analytics: UA-79936770-6 # replace with your GA tracking identifier
google_analytics_v4: G-VN3XBCPWZE

# Permalinks
permalink: /:title
# permalink: /author/:author
# permalink: /tag/:tag
#permalink: /:tag/:title

# Authors' info in `_data/authors.yml`
# Tags' info in `_data/tags_info.yml`

# gems and other configs
plugins_dir: [_plugins]
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist, jekyll-sitemap]

feed:
  path: feed.xml

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: False
lsi: False
username: faizanbashir
repo: faizanbashir.github.io
branch: master
relative_source: /
destination: ./_site
production_url:  https://faizanbashir.me/
source_url:  https://github.com/faizanbashir/faizanbashir.github.io/

exclude:
  - assets/css
  - node_modules
  - vendor
  - .travis.yml
  - Gemfile
  - Gemfile.lock
  - GHOST.txt
  - gulpfile.js
  - LICENSE
  - package.json
  - Rakefile
  - README.md
  - script.py
  - changelog.md
  - "*.Rmd"
  - .git*
